### ISSUE TITLE
디자인 시스템 개선

### ISSUE THREAD

**Issue by trycatch98** [trycatch98/Aurora#18]
## 설명
#6 코드 리뷰 피드백을 반영하여 디자인 시스템을 개선

## TODO
- [x] AuroraSeedButton에 disabledTextColor 추가
- [x] 실수로 정의된 사이즈 정수로 변경
- [x] 기본 사이즈 지정을 Modifier가 아닌 width와 같이 따로 분리
- [x] AuroraIndicator size가 current 보다 더 작게 넘어오는 것을 방지
