### ISSUE TITLE
PR #9 코드 리뷰 피드백 적용

### ISSUE THREAD

**Issue by trycatch98** [trycatch98/Aurora#19]
## 설명
PR #9 에서 받은 코드 리뷰 피드백을 반영

## TODO
- [ ] Navigation hashCode 비교 개선
- [x] 이벤트 sealed interface로 변경
- [x] SideEffect를 LaunchedEffect에 등록하는 방식 수정
- [x] pagerState 하드 코딩 수정
- [x] 접근 제한자 검토
